'use client'
import {useEffect,useState} from 'react'
const API=process.env.NEXT_PUBLIC_API_BASE_URL||'http://localhost:8000'
export default function Home(){const [users,setUsers]=useState([]);const [user,setUser]=useState(null);const [msg,setMsg]=useState('');const [rows,setRows]=useState([]);const [busy,setBusy]=useState(false);const [proposals,setProposals]=useState([])
 useEffect(()=>{fetch(`${API}/api/users`).then(x=>x.json()).then(setUsers)},[])
 async function login(id){setRows([]);setProposals([]);const r=await fetch(`${API}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({user_id:id})});setUser(await r.json())}
 async function send(){if(!msg.trim()||!user)return;setBusy(true);const text=msg;setMsg('');setRows(x=>[...x,{kind:'user',text}]);try{const r=await fetch(`${API}/api/chat`,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({message:text})});const d=await r.json();setRows(x=>[...x,{kind:'assistant',text:d.answer,events:d.events}]);const p=d.events?.flatMap(e=>e.result?.status==='pending_confirmation'?[e.result]:[])||[];if(p.length)setProposals(x=>[...x,...p])}catch(e){setRows(x=>[...x,{kind:'assistant',text:'The support service is waking up or unavailable. Please retry.'}])}finally{setBusy(false)}}
 async function confirm(id){const r=await fetch(`${API}/api/actions/${id}/confirm`,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({confirmed:true})});const d=await r.json();setRows(x=>[...x,{kind:'system',text:d.status==='created'?`Escalation created: ${d.action_id}`:d.detail}]);setProposals(x=>x.filter(p=>p.proposal_id!==id))}
 if(!user)return <main className="shell"><h1>ParcelPilot Support Copilot</h1><p>Internal demo auth — choose a role.</p><div className="roles">{users.map(u=><button key={u.user_id} onClick={()=>login(u.user_id)}>{u.user_id} · {u.role}</button>)}</div></main>
 return <main className="shell"><header><div><h1>ParcelPilot Support Copilot</h1><small>{user.role} · {user.all_accounts?'all accounts':user.allowed_account_ids.join(', ')}</small></div><button onClick={()=>{setUser(null);setRows([]);setProposals([]);fetch(`${API}/api/auth/logout`,{method:'POST',credentials:'include'})}}>Sign out</button></header><section className="chat">{rows.map((r,i)=><article className={r.kind} key={i}><div>{r.text}</div>{r.events?.map((e,j)=><span className="tool" key={j}>tool: {e.name} · {e.status}</span>)}</article>)}{busy&&<article className="assistant">Working through scoped records and authoritative sources…</article>}</section><div className="composer"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about an order, ticket, SLA, cancellation, or credit…"/><button onClick={send} disabled={busy}>Send</button></div>{proposals.map(p=><div className="proposal" key={p.proposal_id}><strong>Pending confirmation</strong><p>{p.summary}</p><button onClick={()=>confirm(p.proposal_id)}>Confirm escalation</button></div>)}</main>}
